micronaut:
  application:
    name: linketindermicronaut
  server:
    port: 8082
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/linketinderspring
    driverClassName: org.postgresql.Driver
    username: arthur
    password: 123456
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3


